export const GETALL_REQUEST = 'USERS_GETALL_REQUES';
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
export const GETALL_ERROR = 'USERS_GETALL_ERROR';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUES';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_ERROR = 'USERS_REGISTER_ERROR';

export const DELETE_REQUEST = 'USERS_DELETE_REQUES';
export const DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const DELETE_ERROR = 'USERS_DELETE_ERROR';
